package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Mail;
import greendao.SNS;
import greendao.Web;
import greendao.Computer;
import greendao.Shopping;
import greendao.Credit;
import greendao.Bank;
import greendao.Other;

import greendao.MailDao;
import greendao.SNSDao;
import greendao.WebDao;
import greendao.ComputerDao;
import greendao.ShoppingDao;
import greendao.CreditDao;
import greendao.BankDao;
import greendao.OtherDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mailDaoConfig;
    private final DaoConfig sNSDaoConfig;
    private final DaoConfig webDaoConfig;
    private final DaoConfig computerDaoConfig;
    private final DaoConfig shoppingDaoConfig;
    private final DaoConfig creditDaoConfig;
    private final DaoConfig bankDaoConfig;
    private final DaoConfig otherDaoConfig;

    private final MailDao mailDao;
    private final SNSDao sNSDao;
    private final WebDao webDao;
    private final ComputerDao computerDao;
    private final ShoppingDao shoppingDao;
    private final CreditDao creditDao;
    private final BankDao bankDao;
    private final OtherDao otherDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mailDaoConfig = daoConfigMap.get(MailDao.class).clone();
        mailDaoConfig.initIdentityScope(type);

        sNSDaoConfig = daoConfigMap.get(SNSDao.class).clone();
        sNSDaoConfig.initIdentityScope(type);

        webDaoConfig = daoConfigMap.get(WebDao.class).clone();
        webDaoConfig.initIdentityScope(type);

        computerDaoConfig = daoConfigMap.get(ComputerDao.class).clone();
        computerDaoConfig.initIdentityScope(type);

        shoppingDaoConfig = daoConfigMap.get(ShoppingDao.class).clone();
        shoppingDaoConfig.initIdentityScope(type);

        creditDaoConfig = daoConfigMap.get(CreditDao.class).clone();
        creditDaoConfig.initIdentityScope(type);

        bankDaoConfig = daoConfigMap.get(BankDao.class).clone();
        bankDaoConfig.initIdentityScope(type);

        otherDaoConfig = daoConfigMap.get(OtherDao.class).clone();
        otherDaoConfig.initIdentityScope(type);

        mailDao = new MailDao(mailDaoConfig, this);
        sNSDao = new SNSDao(sNSDaoConfig, this);
        webDao = new WebDao(webDaoConfig, this);
        computerDao = new ComputerDao(computerDaoConfig, this);
        shoppingDao = new ShoppingDao(shoppingDaoConfig, this);
        creditDao = new CreditDao(creditDaoConfig, this);
        bankDao = new BankDao(bankDaoConfig, this);
        otherDao = new OtherDao(otherDaoConfig, this);

        registerDao(Mail.class, mailDao);
        registerDao(SNS.class, sNSDao);
        registerDao(Web.class, webDao);
        registerDao(Computer.class, computerDao);
        registerDao(Shopping.class, shoppingDao);
        registerDao(Credit.class, creditDao);
        registerDao(Bank.class, bankDao);
        registerDao(Other.class, otherDao);
    }
    
    public void clear() {
        mailDaoConfig.getIdentityScope().clear();
        sNSDaoConfig.getIdentityScope().clear();
        webDaoConfig.getIdentityScope().clear();
        computerDaoConfig.getIdentityScope().clear();
        shoppingDaoConfig.getIdentityScope().clear();
        creditDaoConfig.getIdentityScope().clear();
        bankDaoConfig.getIdentityScope().clear();
        otherDaoConfig.getIdentityScope().clear();
    }

    public MailDao getMailDao() {
        return mailDao;
    }

    public SNSDao getSNSDao() {
        return sNSDao;
    }

    public WebDao getWebDao() {
        return webDao;
    }

    public ComputerDao getComputerDao() {
        return computerDao;
    }

    public ShoppingDao getShoppingDao() {
        return shoppingDao;
    }

    public CreditDao getCreditDao() {
        return creditDao;
    }

    public BankDao getBankDao() {
        return bankDao;
    }

    public OtherDao getOtherDao() {
        return otherDao;
    }

}
